packages/uppy-react/scan.js
=> fix(uppy-react): account for upload-result header

README.md
Updates the README with links to the new components.
=> chore(docs): updated readme

packages/breadcrumbs/Breadcrumbs.js, packages/breadcrumbs/tests/Breadcrumbs.reactrouter.test.js, packages/docs/stories/page-header.stories.js, packages/page-header/PageHeader.d.ts, packages/page-header/PageHeader.js, packages/page-header/README.md, packages/page-header/tests/__snapshots__/PageHeader.test.js.snap
I modified the Pageheader to use the new dynamic Breadcrumbs.
Props validation added for crumbs and custom children BreadcrumbItems
=> feat: integrated dynamic breadcrumbs into PageHeader

packages/docs/stories/payer-logo.stories.js, packages/payer-logo/PayerLogo.d.ts, packages/payer-logo/PayerLogo.js, packages/payer-logo/README.md, packages/payer-logo/tests/PayerLogo.test.js
BREAKING CHANGE: clientId prop is required. it is needed in order to
call slotmachine
=> fix(payer-logo): send clientId in request to slotmachine

packages/pagination/README.md, packages/pagination/src/Pagination.js, packages/pagination/src/PaginationControls.js
BREAKING CHANGE: pagination provider returns page count rather than array of pages
=> fix(pagination): fixed range error when records go over a certain limit

packages/docs/stories/upload.stories.js, packages/upload/README.md, packages/upload/Upload.d.ts, packages/upload/Upload.js, packages/upload/UploadProgressBar.js
Let me know if anything else needs to be done.
=> Restricting special characters in attachment names

packages/docs/stories/upload.stories.js, packages/upload/README.md, packages/upload/Upload.d.ts, packages/upload/Upload.js, packages/upload/UploadProgressBar.js
Reverts Availity/availity-react#92
Unit Tests are failing.
=> Revert "Restricting special characters in attachment names"

CONTRIBUTING.md, package.json
Adds testing before commit-lint.
Adds Contributing doc.
=> docs: added contributing docs and added pre-commit hook for test

packages/page-header/PageHeader.js
**FIXES**
- destructure space from useSpace
- define logo lower in sequence
=> fix(page-header): correct usage of useSpace

packages/pagination/src/PaginationControls.js, packages/pagination/src/__test__/PaginationControls.test.js
=> feat(pagination): prev and next text on buttons

packages/docs/stories/data/availity-spaces-response.json, packages/docs/stories/spaces.stories.js, packages/spaces/README.md, packages/spaces/index.js, packages/spaces/src/Spaces.js, packages/spaces/src/SpacesGhostText.js, packages/spaces/tests/SpacesGhostText.test.js, packages/spaces/types/SpacesGhostText.d.ts
=> feat(spaces): add SpacesGhostText component

packages/pagination/README.md, packages/pagination/src/Pagination.js, packages/pagination/src/__test__/Pagination.test.js, packages/pagination/types/Pagination.d.ts
=> feat(pagination): add resetParams prop

packages/spaces/README.md, packages/spaces/src/Spaces.js, packages/spaces/tests/Spaces.test.js, packages/spaces/types/Spaces.d.ts
closes #165 
gives consumer of the spaces package the ability to pass spaces into the
spaces provider rather than being forced to have them fetched from
slotmachine
=> add spaces prop to spaces package

packages/hooks/README.md
=> docs(hooks): corrected code block markdown

packages/reactstrap-validation-select/AvSelect.js, packages/reactstrap-validation-select/styles.scss
=> refactor(reactstrap-validation-select): added stylesheet

package.json, packages/authorize/Authorize.js, packages/authorize/README.md, packages/authorize/index.d.ts, packages/authorize/index.js, packages/authorize/tests/useAuthorize.test.js, packages/authorize/useAuthorize.d.ts, packages/authorize/useAuthorize.js, packages/docs/stories/authorize.stories.js, packages/reactstrap-validation-date/tests/AvDate.test.js, packages/reactstrap-validation-select/tests/AvSelect.test.js, packages/reactstrap-validation-select/tests/__snapshots__/AvSelect.test.js.snap, packages/upload/FileRow.js
Adds a custom hook for `Authorize`.
Todos
=> feat(authorize): adds custom react hook

packages/reactstrap-validation-select/resource-components.js
Styling only change to patient dropdown options per ux feedback. No
functionality changes
=> refactor(reactstrap-validation-select): update patient option styling

package.json, packages/docs/stories/avselect.stories.js, packages/docs/stories/mocks/AvFormResults.js, packages/reactstrap-validation-select/resource-components.js, packages/reactstrap-validation-select/resources.js
this is to handle the "creatable" use case in `<AvPatientSelect />`. We may not always have all the patient information to show as the value in the dropdown as it is currently designed.
=> refactor(reactstrap-validation-select): show lastName as patient value

packages/docs/stories/hooks.stories.js, packages/hooks/README.md, packages/hooks/index.d.ts, packages/hooks/index.js, packages/hooks/src/useCurrentUser.js, packages/hooks/tests/useCurrentUser.test.js, packages/hooks/typings/useCurrentUser.d.ts
This hook fetches the currently logged in user
=> feat(hooks): added useCurrentUser hook

README.md
=> chore: added note in readme about data-testid [skip-ci]

packages/select/src/Select.js
=> fix(select): changed menu item color to black

packages/docs/stories/avdate.stories.js, packages/reactstrap-validation-date/src/AvDateRange.js, packages/reactstrap-validation-date/tests/AvDateRange.test.js
This is a fix for the datepicker and inputs setting values incorrectly in AvDateRange when using default start and end dates.
=> fix(reactstrap-validation-date): fix for default start and end dates

packages/form/src/Checkbox.js, packages/form/src/CheckboxGroup.js, packages/form/src/Radio.js, packages/form/src/RadioGroup.js, packages/form/tests/CheckboxGroup.test.js, packages/form/tests/RadioGroup.test.js, packages/form/typings/CheckboxGroup.d.ts, packages/form/typings/RadioGroup.d.ts
fixes #253 
feat(form): Added `onChange` callback for `CheckboxGroup` and `RadioGroup`.
=> refactor(form): added callback for radio and checkbox groups

packages/docs/gatsby-config.js, packages/docs/package.json, yarn.lock
Upgrades gatsby docs to latest theme version.
=> refactor(docs): updated gatsby theme

packages/date/typings/DateField.d.ts, packages/date/typings/DateRangeField.d.ts, packages/feedback/typings/FeedbackForm.d.ts, packages/form/typings/Checkbox.d.ts, packages/form/typings/CheckboxGroup.d.ts, packages/form/typings/Field.d.ts, packages/form/typings/Radio.d.ts, packages/form/typings/RadioGroup.d.ts, packages/reactstrap-validation-date/typings/AvDateField.d.ts, packages/reactstrap-validation-date/typings/AvDateRangeField.d.ts, packages/reactstrap-validation-select/AvResourceSelect.d.ts, packages/reactstrap-validation-select/AvSelectField.d.ts, packages/select/typings/SelectField.d.ts
=> Fixes Typescript Definitions For Label Props

packages/reactstrap-validation-select/AvResourceSelect.js, packages/reactstrap-validation-select/tests/AvResourceSelect.test.js, packages/select/src/ResourceSelect.js, packages/select/tests/ResourceSelect.test.js
=> fix(select): fixes multiple API calls on component mount

packages/date/src/DateField.js, packages/date/src/DateRangeField.js, packages/date/tests/DateField.test.js, packages/date/tests/DateRange.test.js, packages/date/tests/DateRangeField.test.js, packages/date/typings/DateField.d.ts, packages/date/typings/DateRangeField.d.ts, packages/docs/source/form/date/components/date-field.md, packages/docs/source/form/date/components/date-range-field.md
Creating this again because I messed the other one up rebasing...
=> feat(date): added additional attributes to the label for DateField and DateRangeField
