Availity/availity-react

- packages/uppy-grill/FileItem.js
- packages/uppy-grill/style.scss
Currently, after a file has been uploaded if a user changes the meta data the data is not saved. This is because the file has already been uploaded.
This update makes the metadata files disabled when a file is being uploaded or has been uploaded.
It also adds the ability to remove uploaded files.
The use-case for all of this is when the files are uploaded prior to submitting another form with references to the files.
> feat: uppy-grill disable metadata fields for updated files

- packages/docs/stories/reactstrap-validation-select.stories.js
- packages/reactstrap-validation-select/AvResourceSelect.js
- packages/reactstrap-validation-select/AvSelect.js
- packages/reactstrap-validation-select/AvSelectField.js
- packages/reactstrap-validation-select/README.md
- packages/reactstrap-validation-select/resources.js
Add ability to watch params for changes and reload the options when any of the watched parameters have changed.
This is useful when since a changing parameter may completely change the options loaded
Note: this only affect the AvResourceSelect and things based on it
> feat(reactstrap-validation-select): add ability to reload options

- packages/upload/FilePicker.js
Warning: Failed prop type: Invalid prop `size` of type `number` supplied to `Input`, expected `string`.
in Input (created by FilePicker)
in FilePicker (created by FilePickerBtn)
> fix(upload)Input expects string for size attribute

- packages/reactstrap-validation-select/styles.scss
How Current styles look: 
With style changes: 
One change not seen here that could be added to PR, in my use I needed to add this in order to make sure the dropdown rendered above some stuff lower in the page with z-indexes changed in our UI-kit. Would it be worth adding this to the css? 
```javascript
styles: {{
menu: styles => ({ ...styles, zIndex: 5 }),
}}
```
> fix(reactstrap-validation-select): update styles in input-groups

- package-lock.json
- packages/breadcrumbs/Breadcrumbs.js
- packages/breadcrumbs/tests/__snapshots__/Breadcrumbs.test.js.snap
- packages/page-header/PageHeader.js
- packages/page-header/tests/__snapshots__/PageHeader.test.js.snap
Updated Aria Attributes for:
- Breadcrumbs: added aria-labels for `a` tags.
- Page Header: Only 1 `h1` tag is allowed per page. We should not be putting the h1 element inside the page header in the case its not the main element of focus.
> refactor(feature): updated aria attributes

- README.md
- packages/docs/package.json
- packages/docs/stories/hooks.stories.js
- packages/hooks/README.md
- packages/hooks/index.d.ts
- packages/hooks/index.js
- packages/hooks/package-lock.json
- packages/hooks/package.json
- packages/hooks/tests/useEffectAsync.test.js
- packages/hooks/tests/useToggle.test.js
- packages/hooks/useEffectAsync.d.ts
- packages/hooks/useEffectAsync.js
- packages/hooks/useToggle.d.ts
- packages/hooks/useToggle.js
Created some simple hooks that are going to be re-used across projects. There are already a number of libraries out there right now with a bunch of hooks but its still too early to pick one as they are all volatile. 
Eventually we can implement an external hooks library but for now there are only a very small amount that we need and will minimize the bundle footprint since a lot of these other libs are 10kb+.
Once this or another lib is accepted the other components in the library can easily be migrated to hooks due to the minor version bump of React 16.
> feat(hooks): added new package containing common hooks

- packages/docs/package.json
The `payer-logo` component pulls static url's for the logos in which they are not present in the build folder due to the exclusion of the `./static` folder.
> fix(docs): static file path was not being pulled correctly

- packages/breadcrumbs/Breadcrumbs.js
- packages/page-header/PageHeader.js
The prop validation for breadcrumb item type was causing some headaches. In some scenarios with `react-hot-loader` the `type.name` of the component changes to `ProxyFacade` and you can revert to the displayName but that is also a changeable feature.
> fix(breadcrumbs): removed prop validation for breadcrumb item type

- packages/breadcrumbs/Breadcrumbs.js
Simply just spreads the remaining props in the `Breadcrumbs` component to the reactstrap comp.
Useful for adding extra classNames etc.
> chore(breadcrumbs): spread remaining props to breadcrumbs component

- packages/breadcrumbs/Breadcrumbs.js
Since BreadCrumbItem is compiles to a `<li>` tag it is required for a11y validation.
https://dequeuniversity.com/rules/axe/3.1/list?application=AxeChrome
> refactor(breadcrumbs): changed tag element for feedback to li

- packages/pagination/src/PaginationContent.js
- packages/pagination/src/PaginationControls.js
PaginationContent:
- Added containerProps for passing additional props to the container. Kept the `containerTag` prop so we can keep as a minor change.
PaginationControls:
- Added `aria-label` to announce control as `Page 1` rather than `Item 1, Button`.
- Added `aria-current` to announce the selected page as the active one.
> refactor(pagination): added aria attrs and container props

- packages/docs/.storybook/webpack.config.js
- packages/docs/package.json
Looks like turning the debug logs for the build to off decreased the build time by 30 seconds and also removing the ts loaders helped some as well.
> chore(docs): trying to increase performance on the doc builds

- packages/app-icon/AppIcon.d.ts
- packages/app-icon/AppIcon.js
- packages/app-icon/README.md
- packages/app-icon/tests/AppIcon.test.js
- packages/docs/stories/app-icon.stories.js
- packages/docs/stories/page-header.stories.js
- packages/page-header/PageHeader.d.ts
- packages/page-header/PageHeader.js
- packages/page-header/README.md
In some cases users can use a logo or image for the app icon and still maintain the proper aspect ratios. Added in `src` and `alt` props if you want to display the `AppIcon` as an image.
> feat(app-icon): added image src and alt properties to app-icon

- packages/favorites/FavoritesContext.js
- packages/favorites/index.js
Gives the ability for someone to `useContext(FavoritesContext)` and be able to use all the favorites in a component rather than 1 by 1.
Useful for the nav where we display all of the favorites in the navbar.
> feat(favorites): added export for context

- packages/reactstrap-validation-date/AvDateRange.js
fix to work when the start name uses lodash syntax (ex. `date.start`).
> fix(reactstrap-validation-date): fix distance validation

- README.md
- packages/docs/package.json
- packages/docs/stories/link.stories.js
- packages/link/CHANGELOG.md
- packages/link/Link.d.ts
- packages/link/Link.js
- packages/link/README.md
- packages/link/index.d.ts
- packages/link/index.js
- packages/link/package.json
- packages/link/test/Link.test.js
A simple link component that handles the logic to make urls compatible for loadApp. Meaning, it renders a link that when clicked in a new tab, will open inside the iframe of the home page.
> feat: add link component

- packages/breadcrumbs/package.json
- packages/docs/package.json
- packages/favorites/package.json
- packages/feedback/package.json
- packages/list-group-item/package.json
- packages/list-group/package.json
- packages/pagination/package.json
- packages/pagination/src/PaginationControls.js
- packages/reactstrap-validation-date/package.json
- packages/reactstrap-validation-select/package.json
- packages/upload/package.json
closes #101 
Every breaking change we make for any future components we can also just require the upgrade of reactstrap to v8 to eventually dump support for previous major versions.
> Updated Reactstrap

- packages/favorites/FavoritesContext.js
- packages/favorites/__test__/FavoriteHeart.test.js
corrects issue where when a favorite is unfavorited, it's not removed from the payload sent in the post message sent to `window.parent`. We fix this by sending the favorites returned from the settings api in the post message
> fix(favorites): fix favorites sent in avMessage when favorites deleted

- packages/reactstrap-validation-date/AvDate.js
- packages/reactstrap-validation-date/AvDateRange.js
- packages/reactstrap-validation-date/tests/__snapshots__/AvDate.test.js.snap
The input-group-addon automatically adds a z-index:2 onto any nested button component inside. Fixed this by adding a hardcoded z-index style to the button component that gets the class.
> fix(reactstrap-validation-date): fixed z-index issue

- packages/favorites/FavoritesContext.js
- packages/favorites/__test__/FavoriteHeart.test.js
when `addFavorite` gets run, we send a post message to parent with the result of the settings call, letting the parent know of new favorites.
> fix(favorites): send post message to window.parent when favorite added

- packages/reactstrap-validation-select/AvSelect.js
> fix(reactstrap-validation-select): fix width of multivalue options

- packages/reactstrap-validation-date/AvDate.js
- packages/reactstrap-validation-date/AvDateRange.js
- packages/reactstrap-validation-date/README.md
- packages/reactstrap-validation-date/package.json
- packages/reactstrap-validation-date/tests/__snapshots__/AvDate.test.js.snap
For anyone not using the `availity-uikit` you can pass in your own calendarIcon to the calendar component. Alternatively, we could just include the calendar icon font with the component.
> refactor(reactstrap-validation-date): added prop for changing out icon

- .eslintrc.yml
- packages/reactstrap-validation-date/AvDate.js
Fixed issue where formatter would think the first inputted value is valid. `dayjs` doesn't accept arrays as formats so we have to iterate.
> fix(reactstrap-validation-date): fixed date auto filling on first type

- README.md
- packages/docs/package.json
- packages/docs/stories/data/availity-spaces-response.json
- packages/docs/stories/mock-requests/slotmachine.js
- packages/docs/stories/spaces.stories.js
- packages/page-header/PageHeader.js
- packages/page-header/README.md
- packages/page-header/package.json
- packages/payer-logo/README.md
- packages/spaces/CHANGELOG.md
- packages/spaces/README.md
- packages/spaces/index.d.ts
- packages/spaces/index.js
- packages/spaces/package.json
- packages/spaces/src/Spaces.js
- packages/spaces/src/SpacesImage.js
- packages/spaces/tests/Spaces.test.js
- packages/spaces/tests/SpacesImage.test.js
- packages/spaces/types/Spaces.d.ts
- packages/spaces/types/SpacesImage.d.ts
This a follow up PR to this PR that I declined: https://github.com/Availity/availity-react/pull/118
The main difference in this PR and the previous one is this one uses React context to expose a Spaces provider. This way, several spaces images can be rendered under a Spaces Provider and we only have to make one ajax request to get the spaces. Another change is this package is no longer intended strictly for images.
As part of this change, I'm proposing:
1. Deprecating the existing @availity/payer-logo package on npm
2. Switching page-header to use `spaces` instead of `payer-logo`
Notes:
I added a deprecation notice to the README of the `payer-logo` package. If it would be preferred to remove it from source control entirely, please let me know.
> feat: add spaces package

- packages/pagination/README.md
- packages/pagination/src/Pagination.js
- packages/pagination/src/__test__/Pagination.test.js
- packages/pagination/types/Pagination.d.ts
For the story I'm working on, I'm replacing some legacy pagination with this newer one, and one of the requirements is that if the user clicks on an item on the page and gets taken to a different page in the same app, then goes back, it needs to be on the same page. Since the component unmounts when we show the other page it loses its state, so with this prop, we can store the current page at a higher level and pass it into the defaultPage prop when we want to show the Pagination again.
Thanks!
> feat(pagination): adding defaultPage prop

- packages/link/Link.d.ts
- packages/link/Link.js
- packages/link/README.md
- packages/link/test/Link.test.js
closes #163 
When `loadApp` is "true", (the default), the `url` prop will be formatted
to leverage "loadApp". When `loadApp` is "false", the `url` prop _will
not_ be formatted to leverage "loadApp".
> feat(link): add loadApp prop

- packages/docs/stories/avdate.stories.js
- packages/reactstrap-validation-date/AvDate.js
- packages/reactstrap-validation-date/AvDateRange.js
BREAKING CHANGE: removed the hideIcon prop in favor of the datepicker prop from the standard date picker to keep the same high level API for showing and hiding the calendar
> refactor(reactstrap-validation-date): fixed datepicker prop for hiding

- packages/spaces/README.md
BREAKING CHANGE: [Commit](https://github.com/Availity/availity-react/pull/170/commits/e9acb794c504ec159949a7fe82ea76c9e4f5c986) was noted as a breaking change but not using the correct conventional commit format for lerna to major bump the package. reactstrap >= 8 is now a peer dep
> refactor(spaces): making breaking change commit to major bump spaces

- packages/app-icon/README.md
- packages/authorize/README.md
- packages/breadcrumbs/README.md
- packages/favorites/README.md
- packages/feature/README.md
- packages/feedback/README.md
- packages/hooks/README.md
- packages/icon/README.md
- packages/link/README.md
- packages/list-group-item/README.md
- packages/list-group/README.md
- packages/page-header/README.md
- packages/pagination/README.md
- packages/payer-logo/README.md
- packages/progress/README.md
- packages/reactstrap-validation-date/README.md
- packages/reactstrap-validation-select/README.md
- packages/spaces/README.md
- packages/step-wizard/README.md
- packages/training-link/README.md
- packages/typography/README.md
- packages/upload/README.md
When you are too lazy to click into the package.json file for each of the components to check their version, we use shields
> docs: added npm version shields to each package

- packages/page-header/PageHeader.js
- packages/spaces/src/SpacesImage.js
- packages/spaces/types/SpacesImage.d.ts
fix(page-header): make skeletonProps.width a string
fix(spaces): only spread skeletonProps onto Loader
resolves prop type warnings
> Fix spaces and page-header prop types

- packages/page-header/PageHeader.js
- packages/page-header/tests/PageHeader.test.js
The current behavior for `useSpace` is to return the first space in the `spaces` array if the value being passed into the hook is `undefined.
This would cause the `space` and `payer` objects to be defined regardless of a `spaceId or `payerId` being passed in. The check is `id === undefined` so defaulting them to null will prevent this from occurring.
> refactor(page-header): updated default props to prevent wrong space

- packages/reactstrap-validation-date/src/AvDate.js
- packages/reactstrap-validation-date/src/AvDateRange.js
- packages/reactstrap-validation-date/styles.scss
When importing the custom styles.scss into a project, if it wasn't import after the import of the datepicker it would not apply our style overrides due to how react-dates applies their style overrides on top. This assures the additional styles are imported in the same file the custom style.scss is imported in
> refactor(reactstrap-validation-date): moved datepicker css into scss

- CONTRIBUTING.md
- README.md
- packages/form/README.md
Also adds additional step in contributing guide to add link to new package. Ideally that would be automated but I don't think there's an easy way to do that with `plop` without sacrificing the packages being in alphabetical order (which is nice IMO)
> docs: add missing package links in README

- packages/page-header/package.json
BREAKING CHANGE: this requires formik and yup to be installed alongside for feedback to work.
I already published a minor version of `page-header` locally to v4.5.3` so that it fixes people who are still on the lower version to use `v4` of feedback.
> chore(page-header): feedback update to latest formik should be major bump

- packages/date/package.json
- packages/docs/package.json
- packages/reactstrap-validation-date/src/AvDateRange.js
- packages/reactstrap-validation-date/tests/AvDateRangeField.test.js
Currently if we had filled out one of the date range fields but not the other it would not error out. The previous datepicker had it to where it would just put the current date of the opposite field into there and call it a day.
I don't think putting the original logic back is good for 508 as its autofilling without the user's consent and without proper reading. Instead we can just display a required message if one of the fields is filled out but not the other.
> refactor(reactstrap-validation-date): single dateRange field filled without other should cause error

- packages/page-header/package.json
BREAKING CHANGE: `@availity/spaces` is now a peer dep.
If someone is using the page-header and also manually using `@availity/spaces` in their web app it will not find the correct context since there will be 2 different versions installed.
> fix(page-header): made spaces peer dep

- packages/form/MIGRATION.md
- packages/form/README.md
> docs(form): add migration guide

- packages/spaces/index.d.ts
- packages/spaces/src/Spaces.js
- packages/spaces/tests/Spaces.test.js
- packages/spaces/types/Spaces.d.ts
Since `useEffect` doesn't allow errors to be bubbled up to a `derivedStateFromErrors` we need to set the error and then return it in the spaces hook in the case someone needs to render an error.
> refactor(spaces): catch error in effect and return error

- package.json
- packages/docs/stories/avdate.stories.js
- packages/icon/Icon.js
- packages/reactstrap-validation-date/CHANGELOG.md
- packages/reactstrap-validation-date/README.md
- packages/reactstrap-validation-date/package.json
- packages/reactstrap-validation-date/src/AvDateRange.js
- packages/reactstrap-validation-date/src/utils.js
- packages/reactstrap-validation-date/tests/AvDateRange.test.js
Adds `ranges` prop back.
- fix(reactstrap-validation-date): derived state from props was not implemented so the value prop was only valid on mount.
- refactor(icon): forwards ref to html element in the case of a ref being passed in
Trying to find a way to test those presets but no dice atm.
> feat(reactstrap-validation-date): added back ranges prop

- packages/reactstrap-validation-select/AvSelectField.d.ts
This is needed when working on Typescript web apps
closes #284
> Updated AvSelectFieldProps to extend AvSelectProps

- packages/breadcrumbs/Breadcrumbs.d.ts
- packages/breadcrumbs/Breadcrumbs.js
- packages/breadcrumbs/tests/Breadcrumbs.test.js
- packages/docs/source/components/breadcrumbs.mdx
- packages/docs/source/components/page-header.mdx
- packages/page-header/PageHeader.d.ts
- packages/page-header/PageHeader.js
- packages/page-header/tests/PageHeader.test.js
- packages/storybook/stories/breadcrumbs.stories.js
- packages/storybook/stories/page-header.stories.js
Adding this in so we can use page header for the gatsby docs.
> refactor(breadcrumbs): changed home url to be overridable

- packages/upload/package.json
I don't think we need all of the possible peer dependencies for `react-dropzone`, but I did not want to break any existing functionality just to fix a warning. I can update if needed.
> chore(upload): updated peer dependency for react-dropzone

- packages/spaces/src/Spaces.js
Removes 3 `useState` calls for one reducer that can handle all the scenarios.
> refactor(spaces): updated state to reducer hooks

- packages/date/src/DateRangeField.js
- packages/date/typings/DateRangeField.d.ts
Previously, the label was not targeting any visible input.
With this change the label will target the start field, enabling the user to click the label to focus on the first field.
> fix(DateRangeField): make label target start field

- packages/date/src/DateField.js
- packages/date/typings/DateField.d.ts
While `FormGroup` `for` prop should be the `name`, `Label`'s `for` prop should be the `id` so that the label is "connected" to the input for a11y and being able to focus on the input when clicking on the label.
> fix(DateField): use id as for in label
